# Generated by Django 4.2.6 on 2023-10-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_author_alter_news_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_url',
            field=models.CharField(blank=True, null=True),
        ),
    ]
